### ISSUE TITLE
silent bonieren ohne logo

### ISSUE THREAD

**Issue by mssack** [cssack/BillingTool#91]
Geht das silent bonieren auch ohne logo?

**Comment by cssack** [comment]
Theoretisch Ja. Allerdings habe ich mich dagegen entschieden weil:
Das erste was das Programm tut ist das Anzeigen dieses Logos.
Wenn ich das nun hinten anstelle und stattdessen zuerst die Commandline interpretiere dauert bei allen anderen Aufrufen dafür das Öffnen des Logos länger.


Ich lass mir das noch mal durch den Kopf gehen eventuell kann ich da trzdm was machen

**Comment by cssack** [comment]
Ich glaub das wird nix, wie wichtig?
